server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: teste123
    url: jdbc:postgresql://localhost:5432/fraud
    username: mkzera
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true